name: new_barfit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_picker_plus: ^1.5.2
  audioplayers: ^6.5.0
  googleapis: any
  googleapis_auth: any
  google_sign_in: any
  http: any
  permission_handler: ^12.0.1
  provider: ^6.0.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/cercleone.png
    - assets/circletwo.png
    - assets/whitecir1.png
    - assets/whitecir2.png
    - assets/calipso.png
    - assets/group.png